### PR TITLE
Added support for both python v2 and v3

### PR DESCRIPTION
**Pull request by 4bitfocus**
I needed this to work with python v2 on my Mac so I put a try/except around the urllib import to fall back to the v2 module. This works on my Mac, but I don't have python v3 handy to test.

### CODE REVIEW

**Comment by bensquire** [comment]
Thanks for this @kevin559er , I haven't merged it as I need an environment to test both the V2 and V3 python scripts...

**Comment by bensquire** [comment]
@ryanwcraig I don't suppose you have python V2 and V3? :)

**Comment by ryanwcraig** [comment]
I do, actually! What do you need me to test? Not too sure how to go about doing that with unmerged code, though.

**Comment by ryanwcraig** [comment]
Just checked, I've got 2.7.8 and 3.4.0!

**Comment by bensquire** [comment]
Excellent :) could you check out Kevins branch?

**Comment by ryanwcraig** [comment]
Sure! I'll report back.

**Comment by ryanwcraig** [comment]
Alright, I was only able to check updater-v2 because i'm not entirely sure what a client ID is (any ideas on that? From digitalocean), but here's the errors I got from the scripts.

Python is 2.7, and python3 is 3.4
screen shot 2015-05-03 at 1 50 44 pm
screen shot 2015-05-03 at 1 51 02 pm

**Comment by bensquire** [comment]
Thanks for checking. The clientID was from the V1 Digital Ocean API (I'm assuming that was when you tested updater.py). I'm not too concerned about that one as they are removing support shortly and I'll be removing the script entirely. However making updater-v2.py work on both v2 & v3 of python would be useful.

Does the:

"__init__() got an unexpected keyword argument 'method'"

mean anything to you @ryanwcraig or @kevin559er ?

**Comment by ryanwcraig** [comment]
Something to do with the constructor, that much I know re:the init() thing.
What the method bit means I'd have to research further.

**Comment by kevin559er** [comment]
There's an open defect about this I believe. It looks like the urllib.request.Request() method no longer takes "method='PUT'" as a key word arg. Apparently a change with Python 3.2.

On May 3, 2015, at 2:18 PM, Ryan Craig <notifications@github.com> wrote:

Something to do with the constructor, that much I know re:the init() thing.
What the method bit means I'd have to research further.

**Comment by kevin559er** [comment]
Small update: It looks like the _method_ key word argument to Request's init was added in Python 3.3.

**Comment by bensquire** [comment]
So in theory this should now work with Python 3.3 & v2?
